### ISSUE TITLE
syntax error in python files 

### ISSUE THREAD

**Issue by iamsonukushwaha** [vinitshahdeo/PortScanner#128]
**Describe the bug**
there are syntax errors in all the python files of **src/** directory

**Screenshots**
![image](https://user-images.githubusercontent.com/51280276/110755219-b7682000-826e-11eb-8348-9e9ee12771e7.png)

**Comment by nitish-awasthi** [comment]
@flyingsonu122 The print statement syntax is valid for python 2.7 for python 3.x check out feature/python 3.8 branch.

**Comment by flyingsonu122** [comment]
we need to 

> @flyingsonu122 The print statement syntax is valid for python 2.7 for python 3.x check out `feature/python 3.8` branch.

we should migrate default branch to python3.8+

**Comment by flyingsonu122** [comment]
@vinitshahdeo everyone (who are working first time on this project) is having problem with this default branch supporting  for python 2.7 

we should **migrate default branch to python3.8+**

**Comment by nitish-awasthi** [comment]
@Kashish121 Please look into this!

**Comment by flyingsonu122** [comment]
@vinitshahdeo @ishika1727  please have a look

**Comment by Kashish121** [comment]
@flyingsonu122 @nitish-awasthi  we'll be switching from *python2.x* to *python3.x* for the `master` branch pretty soon.

> I believe @ranaaditya is working on the same. @ranaaditya, please let me know the status?

**Comment by ranaaditya** [comment]
> @flyingsonu122 @nitish-awasthi  we'll be switching from *python2.x* to *python3.x* for the `master` branch pretty soon.
> 
> > I believe @ranaaditya is working on the same. @ranaaditya, please let me know the status?  

Yeah, I am working on it, soon it will be merged in master.

**Comment by flyingsonu122** [comment]
> > @flyingsonu122 @nitish-awasthi  we'll be switching from _python2.x_ to _python3.x_ for the `master` branch pretty soon.
> > > I believe @ranaaditya is working on the same. @ranaaditya, please let me know the status?
> 
> Yeah, I am working on it, soon it will be merged in master.

@ranaaditya you can see my PR #132 which fixes this and other issues as well

**Comment by guptachitresh** [comment]
@Kashish121 I want to work on this issue. Can you please assign me this?

**Comment by Kashish121** [comment]
@guptachitresh ye please go ahead. I have assigned you this issue. 👍🏽

**Comment by Kashish121** [comment]
Reopened.
