### ISSUE TITLE
No module named '__builtin__'

### ISSUE THREAD

**Issue by iamsonukushwaha** [vinitshahdeo/PortScanner#130]
**Describe the bug**

![image](https://user-images.githubusercontent.com/51280276/110757121-07e07d00-8271-11eb-8898-1a49820d1e96.png)

**To Reproduce**
![image](https://user-images.githubusercontent.com/51280276/110757232-2ba3c300-8271-11eb-84e1-97ef1682bfc3.png)

**Comment by ranaaditya** [comment]
> **Describe the bug**
> 
> ![image](https://user-images.githubusercontent.com/51280276/110757121-07e07d00-8271-11eb-8898-1a49820d1e96.png)
> 
> **To Reproduce**
> ![image](https://user-images.githubusercontent.com/51280276/110757232-2ba3c300-8271-11eb-84e1-97ef1682bfc3.png)

Hi @flyingsonu122 , can you please share your python version of your local system?

Mostly this error comes when you use python 3+, as main branch is compatible with python 2.7. 

can you try [python 3.8](https://github.com/vinitshahdeo/PortScanner/tree/feature/python3.8) branch for python 3+ versions.

Soon we will migrate main branch to python3.8+

thanks !

**Comment by flyingsonu122** [comment]
I am using python 3.8

Definitely we should migrate it to python 3.8

**Comment by flyingsonu122** [comment]
I will create a PR for the same
