### ISSUE TITLE
add GitHub action to request review of PR

### ISSUE THREAD

**Issue by iamsonukushwaha** [vinitshahdeo/PortScanner#134]
**Is your feature request related to a problem? Please describe.**
please add a GitHub action to request review of PR from maintainers

**Describe the solution you'd like**
we can set up GitHub action bot which will request review of PR from maintainers when a PR is created

**Comment by itsIapetus** [comment]
I would like to work on this under GSSOC

**Comment by flyingsonu122** [comment]
> I would like to work on this under GSSOC

how are you going to do it?

**Comment by itsIapetus** [comment]
Using auto request review

**Comment by flyingsonu122** [comment]
> Using auto request review

I am already working on it

**Comment by flyingsonu122** [comment]
@vinitshahdeo @Kashish121 @ishika1727 please assign it to me

**Comment by Kashish121** [comment]
@flyingsonu122 Please DO NOT CREATE A PR before you are assigned the work.

**Comment by iamansoni** [comment]
Is this issue still needs to be addressed!
If yes, you can assign it to me!

**Comment by subhangi2731** [comment]
please assign me this

**Comment by vinitshahdeo** [comment]
@subhangi2731 This is already done, I guess.
