### ISSUE TITLE
empty input value crashes website

### ISSUE THREAD

**Issue by iamsonukushwaha** [vinitshahdeo/PortScanner#136]
**Describe the bug**

pressing **scan now** with empty input value crashes website

![image](https://user-images.githubusercontent.com/51280276/110851513-25e0c880-82d7-11eb-84aa-ffa307e8080c.png)

**Expected changes**
we need to put **required** in the input field

<br/>

![image](https://user-images.githubusercontent.com/51280276/110851380-f5992a00-82d6-11eb-9dfa-40fa37c263b5.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/51280276/110852948-0185eb80-82d9-11eb-8e9a-d6e8169a2b10.png)

**Comment by vinitshahdeo** [comment]
@flyingsonu122 Thanks for reporting this. Adding `gssoc21` label to it.

**Comment by flyingsonu122** [comment]
@vinitshahdeo please look all my PRs

**Comment by flyingsonu122** [comment]
@vinitshahdeo #138 is the PR for the same
