### ISSUE TITLE
Adding Hall of Fame in README.md

### ISSUE THREAD

**Issue by nandikajain** [vinitshahdeo/PortScanner#147]
Adding Hall of Hame in README.md
Github for Hall of Fame repo: https://github.com/sourcerer-io/hall-of-fame
<img width="530" alt="2" src="https://user-images.githubusercontent.com/55681290/111028775-cd1c4780-841e-11eb-953e-344c5666be37.PNG">

**Comment by vinitshahdeo** [comment]
@nandikajain Hey, I guess Hall Of Fame is now deprecated.

**Comment by iamansoni** [comment]
I would like to work on this task!
You can assign it to me!

**Comment by nandikajain** [comment]
> I would like to work on this task!
> You can assign it to me!

Hall of fame is now deprecated. Closing this issue.
