### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by palrohitg** [vinitshahdeo/PortScanner#152]
**Describe the bug**
Undefined variable 'new.py' branch features/python3.8 branch 

**To Reproduce**
1. Just check out the scanner.py you find about the new keyword is not defined. 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/40069230/111041544-a4b43d80-845e-11eb-93e4-f470d81806c7.png)

**Desktop (please complete the following information):**
 - OS: [ubuntu]
 - Browser [brave]
 - Version [latest]

**Additional context**
Want to know what should add in ```absolute_path = os.path.join(new, *split_path)```

**Comment by Kashish121** [comment]
Thank you @palrohitg for identifying this bug. 💯 
This is a small error which can be resolved by changing 
`absolute_path = os.path.join(new, *split_path)` 
to 
`absolute_path = os.path.join(dir, *split_path)`.

Create a PR for the same.

**Comment by palrohitg** [comment]
@Kashish121 done generated.
