### ISSUE TITLE
update contributing .md

### ISSUE THREAD

**Issue by khareyash05** [vinitshahdeo/PortScanner#154]
Hey! I would like to add the following in contributing.md
1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream
I would like to work on it as a part of GSSOC'21

**Comment by KajalSinghBAGHEL** [comment]
can I work on this issue

**Comment by AnjiAgrawal** [comment]
Can I work on this as a participant of GSSOC21?
