### ISSUE TITLE
Add a description about multi-threading

### ISSUE THREAD

**Issue by vinitshahdeo** [vinitshahdeo/PortScanner#16]
Inside [this](https://github.com/vinitshahdeo/PortScanner#performance-using-threads-dart) section, please write a brief description (not more than 3 lines) stating why have we decided to go with multi threading.

> It's always better if we share our findings/knowledge.

**Comment by vinitshahdeo** [comment]
Here you go, @Kashish121!

**Comment by Kashish121** [comment]
Will be up with the description asap.

**Comment by vinitshahdeo** [comment]
@Kashish121 Awesome 👍
