### ISSUE TITLE
Path for config.json is not resolved in scanner.py

### ISSUE THREAD

**Issue by vinitshahdeo** [vinitshahdeo/PortScanner#19]
The relative path of `config.json` is not resolved in `scanner.py` [Reproducible in Windows only]

```python
try:
    with open(file_path('../config.json')) as config_file:
        config = json.load(config_file)
```

Reported by @Kashish121

**Comment by vinitshahdeo** [comment]
@Kashish121 I'm working on this! Will raise the PR soon.

**Comment by vinitshahdeo** [comment]
@Kashish121 If it's working for you, please close this issue.

**Comment by Kashish121** [comment]
Yes this works. 👍
