### ISSUE TITLE
[BUG] CONTRIBUTING.md and Code of Conduct is opening raw file in gh-pages

### ISSUE THREAD

**Issue by vinitshahdeo** [vinitshahdeo/PortScanner#33]
In the deployed GitHub pages [website](https://vinitshahdeo.github.io/PortScanner/), [CONTRIBUTING.md](https://vinitshahdeo.github.io/PortScanner/CONTRIBUTING.md) and [Code of Conduct](https://vinitshahdeo.github.io/PortScanner/CODE_OF_CONDUCT.md) is opening as a raw file. Ideally, it should open as jekyll pages like [DISCLAIMER.md](https://vinitshahdeo.github.io/PortScanner/DISCLAIMER.html)

![Screenshot 2020-06-15 at 10 02 03 PM](https://user-images.githubusercontent.com/20594326/84682840-dfcb2400-af53-11ea-843d-d650ff0a7f29.png)

**Comment by vinitshahdeo** [comment]
@Kashish121 & @ishika1727 - Please triage this issue. I'm fixing this in some time.

**Comment by vinitshahdeo** [comment]
Yes! 🎉 
It's fixed now! :v:

Check now @Kashish121 @ishika1727

**Comment by Kashish121** [comment]
Oh yes! It's fixed already. 🎉
